#######################################################################################
# Training
#######################################################################################
batch_size: 256
num_epochs: 16000
description: burgers
device: cuda:0
seed: 0
pretrained_path: none
save_path: multi-fidelity-mask-pretrained-cnn/weights/transformer/burgers
#######################################################################################
# Model
#######################################################################################
encoder: ViT
encoder_dim: 192
encoder_mlp_dim: 384
encoder_heads: 12
encoder_dim_head: 32
encoder_depth: 4
decoder_dim: 64
decoder_depth: 2
decoder_heads: 8
decoder_dim_head: 16
image_size: 128
patch_size: 16
masking_ratio: 0.75
scheduler: onecycle
min_lr: 0.0001
max_lr: 0.001
beta1: 0.9
beta2: 0.98
pct_start: 0.2
div_factor: 10
final_div_factor: 1000
dropout: 0.0
emb_dropout: 0.0

#######################################################################################
# Data
#######################################################################################
pde: burgers
pde_dim: 2
param_dim: 1
num_samples: 3000
data_path: multi-fidelity-mask-pretrained-cnn/data/burgers/sim
names: ['LF', 'param']
channels: [0,1]